{
 "title": "Shelly Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Device id",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Average power by hour",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "creating-solutions-gcp-shelly",
     "rawSql": "SELECT\r\n  TIMESTAMP_TRUNC(\r\n    TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)),\r\n    HOUR\r\n  ) AS time,\r\n  AVG(FLOAT64(data.params.`switch:0`.apower)) AS avg_power_w\r\nFROM `creating-solutions-gcp-shelly.creating_solutions_with_shelly.ingress_table`\r\nWHERE JSON_VALUE(data, '$.method') = \"NotifyStatus\"\r\n  AND data.params.`switch:0`.apower IS NOT NULL\r\n  AND $__timeFilter(TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)))\r\n  and JSON_VALUE(data.src) = \"$device_id\"\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Timeline of output",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "project": "creating-solutions-gcp-shelly",
     "rawSql": "SELECT\r\n  TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)) AS time,\r\n  data.params.`switch:0`.output AS state,\r\n  data.src AS device_id\r\nFROM `creating-solutions-gcp-shelly.creating_solutions_with_shelly.ingress_table`\r\nWHERE data.params.`switch:0`.output IS NOT NULL\r\nand JSON_VALUE(data.src) = \"$device_id\"\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Fridge data",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "dataset": "creating_solutions_with_shelly",
     "project": "creating-solutions-gcp-shelly",
     "rawSql": "SELECT device_id, timestamp, consumption FROM `creating-solutions-gcp-shelly.creating_solutions_with_shelly.fridge_data` \r\nwhere $__timeFilter(timestamp) "
    }
   ]
  },
  {
   "title": "Power usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "project": "creating-solutions-gcp-shelly",
     "rawSql": "SELECT\r\n  data.src AS device_id,\r\n  TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)) AS timestamp,\r\n  IF(STRPOS(JSON_VALUE(data.src),\"em\")=0, FLOAT64(data.params.`switch:0`.apower), \r\n     FLOAT64(data.params.`em1:0`.act_power)) as power\r\nFROM `creating-solutions-gcp-shelly.creating_solutions_with_shelly.ingress_table`\r\nWHERE \r\n  (data.params.`switch:0`.apower IS NOT NULL or data.params.`em1:0`.act_power is not null)\r\n  and JSON_VALUE(data.src) = \"$device_id\"\r\n  and $__timeFilter(TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)))\r\nORDER BY timestamp\r\n"
    }
   ]
  },
  {
   "title": "Power usage",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 5 },
   "targets": [
    {
     "project": "creating-solutions-gcp-shelly",
     "rawSql": "SELECT\r\n  data.src AS device_id,\r\n  TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)) AS timestamp,\r\n  IF(STRPOS(JSON_VALUE(data.src),\"em\")=0, FLOAT64(data.params.`switch:0`.apower), \r\n     FLOAT64(data.params.`em1:0`.act_power)) as power\r\nFROM `creating-solutions-gcp-shelly.creating_solutions_with_shelly.ingress_table`\r\nWHERE \r\n  (data.params.`switch:0`.apower IS NOT NULL or data.params.`em1:0`.act_power is not null)\r\n  and JSON_VALUE(data.src) = \"$device_id\"\r\n  and $__timeFilter(TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)))\r\nORDER BY timestamp\r\n"
    }
   ]
  },
  {
   "title": "Room temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "creating-solutions-gcp-shelly",
     "rawSql": "select\r\n    FLOAT64(data.params.`bthomesensor:202`.value) as temperature,\r\n    TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)) AS time\r\nfrom `creating-solutions-gcp-shelly.creating_solutions_with_shelly.ingress_table`\r\nwhere JSON_VALUE(data.src) = \"shellyplugsg3-3030f9eaa9d0\"\r\n  and data.params.`bthomesensor:202`.value is not null\r\norder by time desc\r\nlimit 1"
    }
   ]
  },
  {
   "title": "Event logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 11 },
   "targets": [
    {
     "project": "creating-solutions-gcp-shelly",
     "rawSql": "SELECT\r\n  TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)) AS time,\r\n  CONCAT(\r\n    TO_JSON_STRING(data.src),\r\n      ' | ',\r\n    TO_JSON_STRING(data.params.events)\r\n  ) AS message\r\nFROM `creating-solutions-gcp-shelly.creating_solutions_with_shelly.ingress_table`\r\nWHERE JSON_VALUE(data.method, '$') = \"NotifyEvent\"\r\n  AND $__timeFilter(TIMESTAMP_SECONDS(LAX_INT64(data.params.ts)))\r\nORDER BY time DESC\r\n"
    }
   ]
  }
 ]
}